---
- hosts: sonarqube
  become: true
  vars:
    sonarqube_data_volume: /ubuntu/sonarqube
    sonarqube_port: 9000
    arch_mapping:  # Map ansible architecture {{ ansible_architecture }} names to Docker's architecture names
      x86_64: amd64
      aarch64: arm64

  tasks:
    - name: Update and upgrade all packages to the latest version
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        cache_valid_time: 3600

    - name: Install required packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common

    - name: Create directory for Docker's GPG key
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker's official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /etc/apt/keyrings/docker.gpg
        state: present

    - name: Print architecture variables
      ansible.builtin.debug:
        msg: "Architecture: {{ ansible_architecture }}, Codename: {{ ansible_lsb.codename }}"

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: >-
          deb [arch={{ arch_mapping[ansible_architecture] | default(ansible_architecture) }}
          signed-by=/etc/apt/keyrings/docker.gpg]
          https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        filename: docker
        state: present

    - name: Install Docker and related packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

    - name: Set permissions on Docker socket
      file:
        path: /var/run/docker.sock
        mode: '0666'

    - name: Pull SonarQube Docker image
      docker_image:
        name: sonarqube:lts-community
        state: present
        source: pull

    - name: Run SonarQube container
      docker_container:
        name: sonarqube
        image: sonarqube:lts-community
        state: started
        restart_policy: unless-stopped
        ports:
          - "{{ sonarqube_port }}:9000"
        volumes:
          - "sonarqube_data:/opt/sonarqube/data"
          - "/var/run/docker.sock:/var/run/docker.sock"

  handlers:
    - name: Restart Docker
      service:
        name: docker
        state: restarted


